apiVersion: v1
kind: Service
metadata:
  name: aquavid
  namespace: video
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: aquavid
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30210